In [1]:
##Analisis region code

In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [3]:
df=pd.read_csv('C:/Users/evive/Downloads/Nico y Juan/easyMoney/df_banc_rev.csv')

In [4]:
df_region_code_unidades_vendidas = df.groupby('region_code')['unidades_vendidas_total'].sum().reset_index()

In [5]:
df_region_code_unidades_vendidas.sort_values(by = ["unidades_vendidas_total"], ascending = False, inplace = True)

In [6]:
df_region_code_unidades_vendidas

    region_code  unidades_vendidas_total
27         28.0                1295230.0
7           8.0                 553680.0
45         46.0                 385344.0
40         41.0                 310351.0
29         30.0                 300938.0
14         15.0                 261264.0
28         29.0                 202737.0
2           3.0                 193278.0
35         36.0                 181721.0
10         11.0                 168715.0
32         33.0                 144864.0
49         50.0                 139157.0
34         35.0                 137280.0
46         47.0                 124911.0
5           6.0                 119798.0
17         18.0                 105172.0
44         45.0                 104617.0
36         37.0                  97356.0
9          10.0                  83997.0
38         39.0                  81184.0
13         14.0                  80049.0
11         12.0                  76017.0
1           2.0                  74091.0
20         21.0                  74015.0
12         13.0                  72066.0
6           7.0                  67169.0
31         32.0                  56360.0
26         27.0                  53104.0
8           9.0                  53024.0
42         43.0                  48350.0
16         17.0                  46801.0
24         25.0                  43767.0
23         24.0                  41043.0
47         48.0                  40779.0
3           4.0                  37491.0
25         26.0                  36644.0
15         16.0                  36411.0
22         23.0                  35662.0
37         38.0                  33217.0
48         49.0                  32282.0
30         31.0                  32136.0
33         34.0                  29197.0
18         19.0                  24028.0
4           5.0                  22691.0
19         20.0                  22167.0
39         40.0                  21808.0
21         22.0                  21512.0
0           1.0                  15079.0
43         44.0                  12779.0
41         42.0                   9089.0
50         51.0                   3201.0
51         52.0                   2746.0

In [7]:
df_region_code_revenue = df.groupby('region_code')['revenue_total'].sum().reset_index()

In [8]:
df_region_code_revenue.sort_values(by = ["revenue_total"], ascending = False, inplace = True)

In [9]:
df_region_code_revenue

    region_code  revenue_total
27         28.0     27204160.0
7           8.0      8768340.0
45         46.0      6322140.0
40         41.0      5115950.0
29         30.0      4250310.0
14         15.0      3684450.0
2           3.0      3513020.0
28         29.0      3372640.0
10         11.0      2637600.0
35         36.0      2633170.0
34         35.0      2350050.0
32         33.0      2216690.0
49         50.0      2044610.0
46         47.0      1924220.0
17         18.0      1784870.0
44         45.0      1684960.0
5           6.0      1609420.0
38         39.0      1453360.0
36         37.0      1395860.0
13         14.0      1249380.0
11         12.0      1242930.0
6           7.0      1234380.0
9          10.0      1122500.0
20         21.0      1088900.0
12         13.0      1076200.0
1           2.0      1068740.0
8           9.0       866380.0
31         32.0       813090.0
47         48.0       798980.0
42         43.0       768890.0
23         24.0       765760.0
3           4.0       746320.0
26         27.0       736370.0
37         38.0       719120.0
16         17.0       701880.0
22         23.0       697440.0
24         25.0       568040.0
25         26.0       547700.0
30         31.0       516630.0
18         19.0       499640.0
15         16.0       486970.0
48         49.0       478880.0
33         34.0       449620.0
19         20.0       439630.0
4           5.0       371760.0
39         40.0       357650.0
21         22.0       310460.0
0           1.0       285160.0
43         44.0       169280.0
41         42.0       142900.0
50         51.0        64520.0
51         52.0        49480.0